function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 100; // objSlope
	global.__objectDepths[1] = 100; // objSlopeDownLeft
	global.__objectDepths[2] = 100; // objSlopeDownRight
	global.__objectDepths[3] = 100; // objSlopeUpLeft
	global.__objectDepths[4] = 100; // objSlopeUpRight
	global.__objectDepths[5] = 100; // objBlock
	global.__objectDepths[6] = 100; // objMiniBlock
	global.__objectDepths[7] = -10; // objStretchableBlock
	global.__objectDepths[8] = -12; // objBlockEdge
	global.__objectDepths[9] = 0; // objBlockInvis
	global.__objectDepths[10] = 100; // objSlideBlock
	global.__objectDepths[11] = 0; // objBlockFake
	global.__objectDepths[12] = 100; // objSlideBlockR
	global.__objectDepths[13] = 1; // objBossBlock
	global.__objectDepths[14] = 100; // objSlipBlock
	global.__objectDepths[15] = 0; // objSaveBlocker
	global.__objectDepths[16] = 100; // objSlideBlockL
	global.__objectDepths[17] = 1; // objPlatform
	global.__objectDepths[18] = 1; // objMovingPlatform
	global.__objectDepths[19] = 1; // objMovingPlatformNoBounce
	global.__objectDepths[20] = 1; // objBlockRise
	global.__objectDepths[21] = 1; // objBlockFall
	global.__objectDepths[22] = 1; // objSaveMedium
	global.__objectDepths[23] = 1; // objSave
	global.__objectDepths[24] = 1; // objSaveVHard
	global.__objectDepths[25] = 1; // objSaveMediumFlip
	global.__objectDepths[26] = 1; // objSaveFlip
	global.__objectDepths[27] = 1; // objSaveVHardFlip
	global.__objectDepths[28] = 0; // objWarpStart
	global.__objectDepths[29] = 10; // objRoomChanger
	global.__objectDepths[30] = 0; // objWarp
	global.__objectDepths[31] = 0; // objWarpNext
	global.__objectDepths[32] = 0; // objWarpAutosaveNext
	global.__objectDepths[33] = 10; // objOutsideRoomChanger
	global.__objectDepths[34] = -50; // objWater
	global.__objectDepths[35] = -50; // objWater2
	global.__objectDepths[36] = -50; // objWater3
	global.__objectDepths[37] = 11; // objWalljumpR
	global.__objectDepths[38] = 11; // objWalljumpL
	global.__objectDepths[39] = 0; // objJumpRefresher
	global.__objectDepths[40] = -8; // objSign
	global.__objectDepths[41] = 0; // objGravityUp
	global.__objectDepths[42] = 0; // objGravityLeft
	global.__objectDepths[43] = 0; // objGravityRight
	global.__objectDepths[44] = 0; // objGravityDown
	global.__objectDepths[45] = 0; // objFreeTrigger
	global.__objectDepths[46] = 0; // objTriggerButton
	global.__objectDepths[47] = 0; // objKillerTrigger
	global.__objectDepths[48] = 10; // objSpikeTriggerUp
	global.__objectDepths[49] = 10; // objSpikeTriggerRight
	global.__objectDepths[50] = 10; // objSpikeTriggerLeft
	global.__objectDepths[51] = 10; // objSpikeTriggerDown
	global.__objectDepths[52] = 0; // objCherryTrigger
	global.__objectDepths[53] = 0; // objTriggerBossSelect
	global.__objectDepths[54] = 0; // objPlayerKiller
	global.__objectDepths[55] = 10; // objSpikeUp
	global.__objectDepths[56] = 10; // objSpikeRight
	global.__objectDepths[57] = 10; // objSpikeLeft
	global.__objectDepths[58] = 10; // objSpikeDown
	global.__objectDepths[59] = 10; // objMiniUp
	global.__objectDepths[60] = 10; // objMiniRight
	global.__objectDepths[61] = 10; // objMiniLeft
	global.__objectDepths[62] = 10; // objMiniDown
	global.__objectDepths[63] = 0; // objKillerBlock
	global.__objectDepths[64] = 0; // objSpikeParent
	global.__objectDepths[65] = -10; // objCherry
	global.__objectDepths[66] = 0; // objCherryBounce
	global.__objectDepths[67] = 0; // objCherryBounceRandom
	global.__objectDepths[68] = 0; // objCherryBounceLat
	global.__objectDepths[69] = 0; // objCherryBounceVert
	global.__objectDepths[70] = -10; // objCherryPersistant
	global.__objectDepths[71] = -100; // objCherryReflectable
	global.__objectDepths[72] = -100; // objReflectableKiller
	global.__objectDepths[73] = 0; // objKillable
	global.__objectDepths[74] = 0; // objTitleMenu
	global.__objectDepths[75] = 0; // objDifficultyMenu
	global.__objectDepths[76] = -10; // objMainMenu
	global.__objectDepths[77] = -100; // objPauseMenu
	global.__objectDepths[78] = 0; // objSoundTest
	global.__objectDepths[79] = 0; // objMenuParent
	global.__objectDepths[80] = -120; // objOptionsMenu
	global.__objectDepths[81] = -120; // objAudioMenu
	global.__objectDepths[82] = -120; // objGraphicMenu
	global.__objectDepths[83] = -120; // objGameplayMenu
	global.__objectDepths[84] = -120; // objControlsMenu
	global.__objectDepths[85] = -120; // objOtherMenu
	global.__objectDepths[86] = 0; // objSlowdownEffect
	global.__objectDepths[87] = -1010; // objMoneyShower
	global.__objectDepths[88] = -100; // objBossName
	global.__objectDepths[89] = 0; // objTutorial1
	global.__objectDepths[90] = -1000; // objShowLabel
	global.__objectDepths[91] = -1000; // objShakeEffect
	global.__objectDepths[92] = -1000; // objLightEffect
	global.__objectDepths[93] = 0; // objPlatformLight
	global.__objectDepths[94] = -1000; // objCard
	global.__objectDepths[95] = -100; // objClear
	global.__objectDepths[96] = -1000000; // objWorld
	global.__objectDepths[97] = 0; // objCamera
	global.__objectDepths[98] = 0; // objSmoothCamera
	global.__objectDepths[99] = 0; // objPlayMusic
	global.__objectDepths[100] = 10; // objBeatenBosses
	global.__objectDepths[101] = 0; // objMusicLooper
	global.__objectDepths[102] = 0; // objParalyzer
	global.__objectDepths[103] = -10; // objPlayerStart
	global.__objectDepths[104] = -10; // objPlayer
	global.__objectDepths[105] = -11; // objBow
	global.__objectDepths[106] = 0; // objBloodEmitter
	global.__objectDepths[107] = -10; // objBlood
	global.__objectDepths[108] = -1000; // objGameOver
	global.__objectDepths[109] = -100; // objBloodH2
	global.__objectDepths[110] = -12; // objWeaponPlayer
	global.__objectDepths[111] = -1; // objBullet
	global.__objectDepths[112] = -1; // objBulletShotgun
	global.__objectDepths[113] = -15; // objBatHit
	global.__objectDepths[114] = 0; // objPlayerThrower
	global.__objectDepths[115] = -20; // objPlayerHP
	global.__objectDepths[116] = 0; // objShopSign
	global.__objectDepths[117] = 0; // objShopEntrance
	global.__objectDepths[118] = 0; // objShopMain
	global.__objectDepths[119] = 0; // objShopWeapon
	global.__objectDepths[120] = 0; // objShopItem
	global.__objectDepths[121] = 5; // objEssisten
	global.__objectDepths[122] = -1000; // objScreenFrame
	global.__objectDepths[123] = -1000; // objJustReflection
	global.__objectDepths[124] = -1000; // objJustReflection_Eyes
	global.__objectDepths[125] = 0; // objBG
	global.__objectDepths[126] = 100000; // objWallHole
	global.__objectDepths[127] = 0; // objWarning
	global.__objectDepths[128] = 0; // objWarningJustist
	global.__objectDepths[129] = 0; // objBoss1Bullet
	global.__objectDepths[130] = -20; // objBulletJR
	global.__objectDepths[131] = -20; // objBulletJustist
	global.__objectDepths[132] = 0; // objBrick
	global.__objectDepths[133] = 0; // objHealBullet
	global.__objectDepths[134] = 0; // objWarningJR
	global.__objectDepths[135] = 0; // objBoss1
	global.__objectDepths[136] = -1; // objJR
	global.__objectDepths[137] = -3; // objJustist
	global.__objectDepths[138] = 0; // objBoss1_Wings
	global.__objectDepths[139] = -2; // objBoss1_Arms
	global.__objectDepths[140] = -2; // objBoss1_Head
	global.__objectDepths[141] = -1; // objBoss1_Follower
	global.__objectDepths[142] = -1; // objBoss1Bow
	global.__objectDepths[143] = 100000; // objBoss2Door
	global.__objectDepths[144] = 100030; // objBoss2HP
	global.__objectDepths[145] = 0; // objBoss2Warning
	global.__objectDepths[146] = 100010; // objViridian
	global.__objectDepths[147] = 0; // objStarV
	global.__objectDepths[148] = 100030; // objJustularityStarCenter
	global.__objectDepths[149] = 0; // objTornado
	global.__objectDepths[150] = 100030; // objRock
	global.__objectDepths[151] = 100030; // objPropeller
	global.__objectDepths[152] = 100010; // objJustularityWater
	global.__objectDepths[153] = 0; // objJustularityBall
	global.__objectDepths[154] = 100030; // objJustularityBomb
	global.__objectDepths[155] = 0; // objMeteor
	global.__objectDepths[156] = 0; // objJustrimsonParent
	global.__objectDepths[157] = -30; // objJustrimsonA
	global.__objectDepths[158] = -31; // objJustrimsonB_Head
	global.__objectDepths[159] = -30; // objJustrimsonB
	global.__objectDepths[160] = -30; // objJustrimsonC
	global.__objectDepths[161] = -30; // objJustrimsonD
	global.__objectDepths[162] = 0; // objJustrimsonController
	global.__objectDepths[163] = -40; // objJustrimsonA_blade
	global.__objectDepths[164] = -30; // objJustrimsonC_Heart
	global.__objectDepths[165] = -13; // objJustrimson_Block
	global.__objectDepths[166] = -14; // objJustrimson_Water
	global.__objectDepths[167] = -30; // objJustrimsonB_Laser
	global.__objectDepths[168] = -20; // objJustrimsonB_LaserBeam
	global.__objectDepths[169] = 0; // objJustrimsonB_Halo
	global.__objectDepths[170] = 100030; // objJustrimsonC_Center
	global.__objectDepths[171] = -31; // objJustrimsonC_Cherry
	global.__objectDepths[172] = -30; // objJustrimson_Soul
	global.__objectDepths[173] = -30; // objJustrimsonD_Star
	global.__objectDepths[174] = 0; // objJustrimson_Fall
	global.__objectDepths[175] = -1; // objJustinationParent
	global.__objectDepths[176] = 5; // objJustination
	global.__objectDepths[177] = -1; // objJustinationDark
	global.__objectDepths[178] = -1; // objJustinationIce
	global.__objectDepths[179] = -1; // objJustinationLight
	global.__objectDepths[180] = -1; // objJustinationFire
	global.__objectDepths[181] = -10; // objBoss4_BigBullet
	global.__objectDepths[182] = 0; // objBoss4_Spike
	global.__objectDepths[183] = -10; // objBoss4_FruitBomb
	global.__objectDepths[184] = -2; // objBoss4_Ground
	global.__objectDepths[185] = -30; // objBoss4_Effects
	global.__objectDepths[186] = 0; // objJustinationPiece
	global.__objectDepths[187] = -100; // objBigKid_BounceFruit
	global.__objectDepths[188] = -100; // objCrimsonCherry
	global.__objectDepths[189] = -100; // objCrimsonFire
	global.__objectDepths[190] = -105; // objDeadShiratama
	global.__objectDepths[191] = -86; // objBigKid_GayShooter
	global.__objectDepths[192] = -30; // objGayReporter
	global.__objectDepths[193] = -102; // objGayBullet
	global.__objectDepths[194] = -100; // objGayIce
	global.__objectDepths[195] = 0; // objGayTornado
	global.__objectDepths[196] = -100; // objGayFireball
	global.__objectDepths[197] = -100; // objGayGranade
	global.__objectDepths[198] = -100; // objGayBoom
	global.__objectDepths[199] = -100; // objKitty
	global.__objectDepths[200] = -112; // objPirhanaPlant
	global.__objectDepths[201] = -110; // objSolgryn_Water
	global.__objectDepths[202] = -100; // objSolgryn_Spider
	global.__objectDepths[203] = -100; // objBigGeezer_Spike
	global.__objectDepths[204] = -90; // objBigGeezer_Octopus
	global.__objectDepths[205] = -100; // objBigGeezer_Rock
	global.__objectDepths[206] = -100; // objBigGeezer_Hammer
	global.__objectDepths[207] = -100; // objBigGeezer_GreenDude
	global.__objectDepths[208] = -100; // objBigGeezer_GreenDude2
	global.__objectDepths[209] = -100; // objBigGeezer_Bat
	global.__objectDepths[210] = -120; // objK2_MagicUse
	global.__objectDepths[211] = -100; // objK2_Ball
	global.__objectDepths[212] = -100; // objK2_Projectile
	global.__objectDepths[213] = -100; // objK2_Bomb
	global.__objectDepths[214] = -100; // objK2_Laser
	global.__objectDepths[215] = -100; // objK2_Projectile2
	global.__objectDepths[216] = 0; // objK2_PeriodicAttack
	global.__objectDepths[217] = -97; // objK2_Sphere
	global.__objectDepths[218] = -90; // objMoon
	global.__objectDepths[219] = 1000; // objBigKid_BG
	global.__objectDepths[220] = -81; // objBigJust_Healthbar
	global.__objectDepths[221] = -85; // objBigBow
	global.__objectDepths[222] = -83; // objBigKid_Head
	global.__objectDepths[223] = -84; // objBigKid_Body
	global.__objectDepths[224] = -80; // objBigKid_Bullet
	global.__objectDepths[225] = -78; // objBigKid_Water
	global.__objectDepths[226] = 0; // objBigJust_ViewMover
	global.__objectDepths[227] = -85; // objBigGeezer_Head
	global.__objectDepths[228] = 100; // objBigGeezer_BlockEffect
	global.__objectDepths[229] = -82; // objBigGeezer_BG
	global.__objectDepths[230] = -83; // objBigGeezer_Block
	global.__objectDepths[231] = -110; // objGeezer_Text
	global.__objectDepths[232] = -100; // objBigGeezer_Eyes
	global.__objectDepths[233] = -100; // objStickyKeys
	global.__objectDepths[234] = -995; // objNoRespond_Controller
	global.__objectDepths[235] = -1000; // objNoRespond
	global.__objectDepths[236] = -1005; // objNoRespond_Close
	global.__objectDepths[237] = -1005; // objNoRespond_Button
	global.__objectDepths[238] = -85; // objK2_SphereCenter
	global.__objectDepths[239] = -100; // objK2_Boom
	global.__objectDepths[240] = -1000; // objK2_LightEffect
	global.__objectDepths[241] = -87; // objK2_Face


	global.__objectNames[0] = "objSlope";
	global.__objectNames[1] = "objSlopeDownLeft";
	global.__objectNames[2] = "objSlopeDownRight";
	global.__objectNames[3] = "objSlopeUpLeft";
	global.__objectNames[4] = "objSlopeUpRight";
	global.__objectNames[5] = "objBlock";
	global.__objectNames[6] = "objMiniBlock";
	global.__objectNames[7] = "objStretchableBlock";
	global.__objectNames[8] = "objBlockEdge";
	global.__objectNames[9] = "objBlockInvis";
	global.__objectNames[10] = "objSlideBlock";
	global.__objectNames[11] = "objBlockFake";
	global.__objectNames[12] = "objSlideBlockR";
	global.__objectNames[13] = "objBossBlock";
	global.__objectNames[14] = "objSlipBlock";
	global.__objectNames[15] = "objSaveBlocker";
	global.__objectNames[16] = "objSlideBlockL";
	global.__objectNames[17] = "objPlatform";
	global.__objectNames[18] = "objMovingPlatform";
	global.__objectNames[19] = "objMovingPlatformNoBounce";
	global.__objectNames[20] = "objBlockRise";
	global.__objectNames[21] = "objBlockFall";
	global.__objectNames[22] = "objSaveMedium";
	global.__objectNames[23] = "objSave";
	global.__objectNames[24] = "objSaveVHard";
	global.__objectNames[25] = "objSaveMediumFlip";
	global.__objectNames[26] = "objSaveFlip";
	global.__objectNames[27] = "objSaveVHardFlip";
	global.__objectNames[28] = "objWarpStart";
	global.__objectNames[29] = "objRoomChanger";
	global.__objectNames[30] = "objWarp";
	global.__objectNames[31] = "objWarpNext";
	global.__objectNames[32] = "objWarpAutosaveNext";
	global.__objectNames[33] = "objOutsideRoomChanger";
	global.__objectNames[34] = "objWater";
	global.__objectNames[35] = "objWater2";
	global.__objectNames[36] = "objWater3";
	global.__objectNames[37] = "objWalljumpR";
	global.__objectNames[38] = "objWalljumpL";
	global.__objectNames[39] = "objJumpRefresher";
	global.__objectNames[40] = "objSign";
	global.__objectNames[41] = "objGravityUp";
	global.__objectNames[42] = "objGravityLeft";
	global.__objectNames[43] = "objGravityRight";
	global.__objectNames[44] = "objGravityDown";
	global.__objectNames[45] = "objFreeTrigger";
	global.__objectNames[46] = "objTriggerButton";
	global.__objectNames[47] = "objKillerTrigger";
	global.__objectNames[48] = "objSpikeTriggerUp";
	global.__objectNames[49] = "objSpikeTriggerRight";
	global.__objectNames[50] = "objSpikeTriggerLeft";
	global.__objectNames[51] = "objSpikeTriggerDown";
	global.__objectNames[52] = "objCherryTrigger";
	global.__objectNames[53] = "objTriggerBossSelect";
	global.__objectNames[54] = "objPlayerKiller";
	global.__objectNames[55] = "objSpikeUp";
	global.__objectNames[56] = "objSpikeRight";
	global.__objectNames[57] = "objSpikeLeft";
	global.__objectNames[58] = "objSpikeDown";
	global.__objectNames[59] = "objMiniUp";
	global.__objectNames[60] = "objMiniRight";
	global.__objectNames[61] = "objMiniLeft";
	global.__objectNames[62] = "objMiniDown";
	global.__objectNames[63] = "objKillerBlock";
	global.__objectNames[64] = "objSpikeParent";
	global.__objectNames[65] = "objCherry";
	global.__objectNames[66] = "objCherryBounce";
	global.__objectNames[67] = "objCherryBounceRandom";
	global.__objectNames[68] = "objCherryBounceLat";
	global.__objectNames[69] = "objCherryBounceVert";
	global.__objectNames[70] = "objCherryPersistant";
	global.__objectNames[71] = "objCherryReflectable";
	global.__objectNames[72] = "objReflectableKiller";
	global.__objectNames[73] = "objKillable";
	global.__objectNames[74] = "objTitleMenu";
	global.__objectNames[75] = "objDifficultyMenu";
	global.__objectNames[76] = "objMainMenu";
	global.__objectNames[77] = "objPauseMenu";
	global.__objectNames[78] = "objSoundTest";
	global.__objectNames[79] = "objMenuParent";
	global.__objectNames[80] = "objOptionsMenu";
	global.__objectNames[81] = "objAudioMenu";
	global.__objectNames[82] = "objGraphicMenu";
	global.__objectNames[83] = "objGameplayMenu";
	global.__objectNames[84] = "objControlsMenu";
	global.__objectNames[85] = "objOtherMenu";
	global.__objectNames[86] = "objSlowdownEffect";
	global.__objectNames[87] = "objMoneyShower";
	global.__objectNames[88] = "objBossName";
	global.__objectNames[89] = "objTutorial1";
	global.__objectNames[90] = "objShowLabel";
	global.__objectNames[91] = "objShakeEffect";
	global.__objectNames[92] = "objLightEffect";
	global.__objectNames[93] = "objPlatformLight";
	global.__objectNames[94] = "objCard";
	global.__objectNames[95] = "objClear";
	global.__objectNames[96] = "objWorld";
	global.__objectNames[97] = "objCamera";
	global.__objectNames[98] = "objSmoothCamera";
	global.__objectNames[99] = "objPlayMusic";
	global.__objectNames[100] = "objBeatenBosses";
	global.__objectNames[101] = "objMusicLooper";
	global.__objectNames[102] = "objParalyzer";
	global.__objectNames[103] = "objPlayerStart";
	global.__objectNames[104] = "objPlayer";
	global.__objectNames[105] = "objBow";
	global.__objectNames[106] = "objBloodEmitter";
	global.__objectNames[107] = "objBlood";
	global.__objectNames[108] = "objGameOver";
	global.__objectNames[109] = "objBloodH2";
	global.__objectNames[110] = "objWeaponPlayer";
	global.__objectNames[111] = "objBullet";
	global.__objectNames[112] = "objBulletShotgun";
	global.__objectNames[113] = "objBatHit";
	global.__objectNames[114] = "objPlayerThrower";
	global.__objectNames[115] = "objPlayerHP";
	global.__objectNames[116] = "objShopSign";
	global.__objectNames[117] = "objShopEntrance";
	global.__objectNames[118] = "objShopMain";
	global.__objectNames[119] = "objShopWeapon";
	global.__objectNames[120] = "objShopItem";
	global.__objectNames[121] = "objEssisten";
	global.__objectNames[122] = "objScreenFrame";
	global.__objectNames[123] = "objJustReflection";
	global.__objectNames[124] = "objJustReflection_Eyes";
	global.__objectNames[125] = "objBG";
	global.__objectNames[126] = "objWallHole";
	global.__objectNames[127] = "objWarning";
	global.__objectNames[128] = "objWarningJustist";
	global.__objectNames[129] = "objBoss1Bullet";
	global.__objectNames[130] = "objBulletJR";
	global.__objectNames[131] = "objBulletJustist";
	global.__objectNames[132] = "objBrick";
	global.__objectNames[133] = "objHealBullet";
	global.__objectNames[134] = "objWarningJR";
	global.__objectNames[135] = "objBoss1";
	global.__objectNames[136] = "objJR";
	global.__objectNames[137] = "objJustist";
	global.__objectNames[138] = "objBoss1_Wings";
	global.__objectNames[139] = "objBoss1_Arms";
	global.__objectNames[140] = "objBoss1_Head";
	global.__objectNames[141] = "objBoss1_Follower";
	global.__objectNames[142] = "objBoss1Bow";
	global.__objectNames[143] = "objBoss2Door";
	global.__objectNames[144] = "objBoss2HP";
	global.__objectNames[145] = "objBoss2Warning";
	global.__objectNames[146] = "objViridian";
	global.__objectNames[147] = "objStarV";
	global.__objectNames[148] = "objJustularityStarCenter";
	global.__objectNames[149] = "objTornado";
	global.__objectNames[150] = "objRock";
	global.__objectNames[151] = "objPropeller";
	global.__objectNames[152] = "objJustularityWater";
	global.__objectNames[153] = "objJustularityBall";
	global.__objectNames[154] = "objJustularityBomb";
	global.__objectNames[155] = "objMeteor";
	global.__objectNames[156] = "objJustrimsonParent";
	global.__objectNames[157] = "objJustrimsonA";
	global.__objectNames[158] = "objJustrimsonB_Head";
	global.__objectNames[159] = "objJustrimsonB";
	global.__objectNames[160] = "objJustrimsonC";
	global.__objectNames[161] = "objJustrimsonD";
	global.__objectNames[162] = "objJustrimsonController";
	global.__objectNames[163] = "objJustrimsonA_blade";
	global.__objectNames[164] = "objJustrimsonC_Heart";
	global.__objectNames[165] = "objJustrimson_Block";
	global.__objectNames[166] = "objJustrimson_Water";
	global.__objectNames[167] = "objJustrimsonB_Laser";
	global.__objectNames[168] = "objJustrimsonB_LaserBeam";
	global.__objectNames[169] = "objJustrimsonB_Halo";
	global.__objectNames[170] = "objJustrimsonC_Center";
	global.__objectNames[171] = "objJustrimsonC_Cherry";
	global.__objectNames[172] = "objJustrimson_Soul";
	global.__objectNames[173] = "objJustrimsonD_Star";
	global.__objectNames[174] = "objJustrimson_Fall";
	global.__objectNames[175] = "objJustinationParent";
	global.__objectNames[176] = "objJustination";
	global.__objectNames[177] = "objJustinationDark";
	global.__objectNames[178] = "objJustinationIce";
	global.__objectNames[179] = "objJustinationLight";
	global.__objectNames[180] = "objJustinationFire";
	global.__objectNames[181] = "objBoss4_BigBullet";
	global.__objectNames[182] = "objBoss4_Spike";
	global.__objectNames[183] = "objBoss4_FruitBomb";
	global.__objectNames[184] = "objBoss4_Ground";
	global.__objectNames[185] = "objBoss4_Effects";
	global.__objectNames[186] = "objJustinationPiece";
	global.__objectNames[187] = "objBigKid_BounceFruit";
	global.__objectNames[188] = "objCrimsonCherry";
	global.__objectNames[189] = "objCrimsonFire";
	global.__objectNames[190] = "objDeadShiratama";
	global.__objectNames[191] = "objBigKid_GayShooter";
	global.__objectNames[192] = "objGayReporter";
	global.__objectNames[193] = "objGayBullet";
	global.__objectNames[194] = "objGayIce";
	global.__objectNames[195] = "objGayTornado";
	global.__objectNames[196] = "objGayFireball";
	global.__objectNames[197] = "objGayGranade";
	global.__objectNames[198] = "objGayBoom";
	global.__objectNames[199] = "objKitty";
	global.__objectNames[200] = "objPirhanaPlant";
	global.__objectNames[201] = "objSolgryn_Water";
	global.__objectNames[202] = "objSolgryn_Spider";
	global.__objectNames[203] = "objBigGeezer_Spike";
	global.__objectNames[204] = "objBigGeezer_Octopus";
	global.__objectNames[205] = "objBigGeezer_Rock";
	global.__objectNames[206] = "objBigGeezer_Hammer";
	global.__objectNames[207] = "objBigGeezer_GreenDude";
	global.__objectNames[208] = "objBigGeezer_GreenDude2";
	global.__objectNames[209] = "objBigGeezer_Bat";
	global.__objectNames[210] = "objK2_MagicUse";
	global.__objectNames[211] = "objK2_Ball";
	global.__objectNames[212] = "objK2_Projectile";
	global.__objectNames[213] = "objK2_Bomb";
	global.__objectNames[214] = "objK2_Laser";
	global.__objectNames[215] = "objK2_Projectile2";
	global.__objectNames[216] = "objK2_PeriodicAttack";
	global.__objectNames[217] = "objK2_Sphere";
	global.__objectNames[218] = "objMoon";
	global.__objectNames[219] = "objBigKid_BG";
	global.__objectNames[220] = "objBigJust_Healthbar";
	global.__objectNames[221] = "objBigBow";
	global.__objectNames[222] = "objBigKid_Head";
	global.__objectNames[223] = "objBigKid_Body";
	global.__objectNames[224] = "objBigKid_Bullet";
	global.__objectNames[225] = "objBigKid_Water";
	global.__objectNames[226] = "objBigJust_ViewMover";
	global.__objectNames[227] = "objBigGeezer_Head";
	global.__objectNames[228] = "objBigGeezer_BlockEffect";
	global.__objectNames[229] = "objBigGeezer_BG";
	global.__objectNames[230] = "objBigGeezer_Block";
	global.__objectNames[231] = "objGeezer_Text";
	global.__objectNames[232] = "objBigGeezer_Eyes";
	global.__objectNames[233] = "objStickyKeys";
	global.__objectNames[234] = "objNoRespond_Controller";
	global.__objectNames[235] = "objNoRespond";
	global.__objectNames[236] = "objNoRespond_Close";
	global.__objectNames[237] = "objNoRespond_Button";
	global.__objectNames[238] = "objK2_SphereCenter";
	global.__objectNames[239] = "objK2_Boom";
	global.__objectNames[240] = "objK2_LightEffect";
	global.__objectNames[241] = "objK2_Face";


	// create another array that has the correct entries
	var len = array_length(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
