image_xscale = 4;
image_yscale = image_xscale;
image_speed = 0.1;
flying = false;
hidden = false;
godmode = false;
canWalk = true;
reviveSound = false;
destinationX = 550;
showing = false;
spd = 4;
state = 0;      //0 - idle, 1 - run, 2 - jump, 3 - fall
sprite[0] = sprJustist_Idle;
sprite[1] = sprJustist_Run;
sprite[2] = sprJustist_Jump;
sprite[3] = sprJustist_Fall;
dick = 0;
oldY = y;
shootCounter = 0;
extraBulletsCounter = 0;
counter = 0;
HP = 100;
energy = 0;
flyHight = random_range(200, 250);
nextFlyHight = flyHight;
nextFlying = flying;
warnDelay = 80 - global.difficulty * 20;
hit = 0;
bro = objJustist;
arms = noone;
color1 = c_red;
color2 = c_maroon;
event_user(0);
event_user(1);
event_user(4);
alarm[8] = irandom_range(1500, 2000);
hole = instance_nearest(x, y, objWallHole);
bullet = noone;
rad = 64;
emitterRevive = part_emitter_create(global.saveParticleSystem);
particleRevive = part_type_create();
part_type_shape(particleRevive,pt_shape_cloud);
part_type_color2(particleRevive, c_red, c_maroon);
part_type_alpha3(particleRevive,0.7485,0.8681,0);
part_type_life(particleRevive,5,100);
part_type_size(particleRevive,1,2,0,0);
part_type_speed(particleRevive,1,2,0,0);
part_type_direction(particleRevive,0,360,0,0);
part_type_orientation(particleRevive,0,360,0,0,0);
part_type_gravity(particleRevive,0,270);
part_type_blend(particleRevive,false);

